### ISSUE TITLE
Decision about if we add w4af to the pip-repository

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#255]
We should decide if we add w4af to the pip-repository and what would be the right time to do so

**Comment by codders** [comment]
For me, there is a fundamental question with Pip of whether we are an application or a library. I feel w4af is an application, and as such it is better suited to a Pipfile / Pipfile.lock installation and deployment. This allows us to very concretely pin our dependencies with cryptographic hashes, so that problems with package-typo-squatting or unexpected uploads to pip repositories that we reference don't directly lead to compromises in the project.

The logic for being a Pip package would suit more if we were a library that other packages depend on. Then it makes sense to be generous / flexible with our upstream dependency versions so that we have maximum compatibility with other packages that might be installed on a system.

The only place where I see a tension, is if we want to be packaged in a linux distribution. In that case we anyway need to support a broader range of upstream dependencies, and at that point if would make sense that we also register a w4af package.

**Comment by security-companion** [comment]
Thanks for your explanation.
I agree that w4af is an application (especially once we have a webclient that controls w4af via the API).
For me it would be nice to being added to a linux distro. But I feel that supporting a broader range of upstream depedencies is quite some work and something that we can currently not handle but the resources we currently have.
So I think for the moment we should not make a pip package and stay with the Pipefile installation and deployment.

**Comment by codders** [comment]
Agreed. Let's stick to the Pipfile for now.
