### ISSUE TITLE
Review and/or remove dependency_check / requirements.py code

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#338]
Hi,
currently we have versions for packages in the pipfile-lock file and in dependency_check/requirements.py.
Am I right that if I want to update a version eg. in order to fix a security fix I need to update version numbers in pipfile-lock and in requirements.py? I think at some point it might happen that because of not being cautious enough versions are not the same in the to files and we run into problems.
Would it not be better to automatically generate the requirements.py file by parsing the pipfile.lock and only have one single-source-of-truth?
Or a more general to understand better: Why do we still need the files in dependency_check? I hope I did not already ask this question before. ;-)

**Comment by codders** [comment]
Hi @security-companion ,

You're right - right now, if there is a change in the Pipfile / Pipfile.lock, there also has to be a change in `depencency_check/requirements.py`, which is a mild pain in the ass. Now that the project is more-or-less pure python and now that we use `pipenv`, the whole `dependency_check` mechanism is anyway of questionable value. There are still a couple of build-time and runtime dependencies that the project needs (for example, libicu-dev at build time, and git at runtime), but I would also be fine just to document those in the README. We just need to think about how to generate meaningful error messages if some of the dependencies are missing, otherwise we end up dealing with a lot more user-support requests.

I don't see it as urgent to make a change for the alpha release.

**Comment by security-companion** [comment]
Okay, I moved this to milestone "After Alpha-release"

**Comment by codders** [comment]
Resolved by #644
